
/*------------------------------------------------------------------------------
                            INDEX FOR TRACKING PURPOSE

- The following are the markers which can be used to identify diffent comments that are linked to same topic

  [CLERK] - clerk provider docs







--------------------------------------------------------------------------------*/


import type { Metadata } from "next";
import { IBM_Plex_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// [CLERK] add the imports for the clerkProvider
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs' 
// now go to return()

// Changing geistSans to Inter
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


// change geistMono to IBM_Plex_Mono
const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // [CLERK] Add <ClerkProvider> here
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.variable} ${plexMono.variable} antialiased`}
        >
          {/* - Add the ThemeProvider component around the child component here 
              - Now we have to add "suppressHydration" warning html tag above
              - Then we can set the theme to dark throgh ThemeProvider
              - This way in future you can change the theme to light or dark throgh the ThemeProvider component
              - Since we are in this layout file, let's modify fonts which are at top
                - This will however not change the font entirely, you have to modify the global.css file too
                - That you can do as homework

              - GOTO notes.md

              */}
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <header>
            {/* [CLERK] Add SignInButton inside SignOut  
                After this is done, 
                GOTO notes.md   */}
            <SignedOut>
              <SignInButton/>
              <SignUpButton>
                <button className="bg-rose-500 text-white">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
            </header>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
